---
# file: roles/jenkins/tasks/install_credentials.yml

- name: "認証情報の追加"
  jenkins_script:
    user: admin
    password: "{{ jenkins_admin_password }}"
    url: "{{ jenkins_url }}"
    validate_certs: no
    script: |
      // グローバルドメインにSSHユーザー名と秘密キーで認証情報を追加する
      import jenkins.model.*
      import com.cloudbees.plugins.credentials.*
      import com.cloudbees.plugins.credentials.common.*
      import com.cloudbees.plugins.credentials.domains.*
      import com.cloudbees.jenkins.plugins.sshcredentials.impl.*
      import hudson.plugins.sshslaves.*

      def credentials = CredentialsProvider.lookupCredentials(
              BasicSSHUserPrivateKey.class,
              Jenkins.instance
          )
      def username = "jenkins"
      def cred = credentials.findResult {
        it.username == username ? it : null
      }
      if (cred == null) {
        credentialsStore = Jenkins.instance.getExtensionList(
            'com.cloudbees.plugins.credentials.SystemCredentialsProvider'
          )[0].getStore()
        def newcred = new BasicSSHUserPrivateKey(
          CredentialsScope.GLOBAL,
          null,
          username,
          new BasicSSHUserPrivateKey.UsersPrivateKeySource(),
          "",
          ""
        )
        globalDomain = Domain.global()
        credentialsStore.addCredentials(globalDomain, newcred)
      }

