# encoding: utf-8

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # DBサーバーの例
  config.vm.define "db" do |node|
    node.vm.box = "centos/7"
    node.vm.hostname = "db"
    # ssh-agentでforwardする
    node.ssh.forward_agent = true
    # IPアドレス
    node.vm.network :private_network, ip: "192.168.33.10"
    # 共有フォルダ
    node.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    node.vm.provider :virtualbox do |vb|
      # メモリはプロジェクトに合わせて変更する
      vb.customize ["modifyvm", :id, "--memory", 512]
    end
    node.vm.provision :shell, :inline => <<-EOT
      # ここで必要なミドルウェアをインストールする
    EOT
  end

end
