---
# file: roles/docker/tasks/main.yml

- name: "Include OS Specific Playbook"
  include_tasks: "{{ item }}"
  with_first_found:
  - "{{ ansible_distribution | lower }}.yml"
  - "{{ ansible_os_family | lower }}.yml"
