version: '2'

services:
  jenkins:
    environment:
      JAVA_OPTS: "-Duser.timezone=Asia/Tokyo -Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Tokyo"
    image: altus5/jenkins-dind:2.60.3
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "{{ jenkins_port }}:8080"
    networks:
      - {{ ci_network_name }}

networks:
  {{ ci_network_name }}:
    external: true
